import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import "./globals.css";
import InstallBootstrap from "../utils/InstallBootstrap";
import NavBar from "../componets/Navigation/NavBar";
import Footer from "@/componets/Footer";
import ThemeContextProvider from "@/context/ThemeContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-bs-theme="dark">
      <ThemeContextProvider>
        <body>
          <InstallBootstrap/>
          <NavBar/>
            <main className="container-fluid">
              {children}
            </main>
          <Footer/>
        </body>
      </ThemeContextProvider>
    </html>
  );
}
